#!/bin/sh
# Applied after the repository's standard network setup.
uci set luci.main.lang='zh_cn'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci -q set openclash.config.enable='0'
uci -q set mosdns.config.enabled='0'
uci -q set daed.config.enabled='0'
uci -q set adguardhome.config.enabled='0'
uci -q set turboacc.config.sw_flow='0'
uci -q set turboacc.config.hw_flow='0'
uci -q set turboacc.config.sfe_flow='0'
uci -q set firewall.@defaults[0].flow_offloading='0'
uci -q set firewall.@defaults[0].flow_offloading_hw='0'
for config in luci openclash mosdns daed adguardhome turboacc firewall; do
    uci commit "$config"
done
for service in openclash mosdns daed adguardhome; do
    /etc/init.d/"$service" disable
done
exit 0
